# Generated by Django 4.2.27 on 2025-12-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='publicado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='visualizacoes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
