# Generated by Django 4.2.27 on 2025-12-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('machado', 'Machado'), ('cajado', 'Cajado'), ('armadura', 'Armadura'), ('variados', 'Variados')], default='variados', max_length=20),
        ),
    ]
