# Generated by Django 4.2.27 on 2025-12-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='raridade',
            field=models.CharField(choices=[('common', 'Comum'), ('rare', 'Raro'), ('epic', 'Épico'), ('legendary', 'Lendário')], default='common', max_length=20),
        ),
    ]
