# Generated by Django 4.2.27 on 2025-12-09 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria de Item',
                'verbose_name_plural': 'Categorias de Itens',
            },
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('nivel', models.PositiveIntegerField(default=1, verbose_name='Nível')),
                ('classe', models.CharField(choices=[('Espadachim', 'Espadachim'), ('Mago', 'Mago'), ('Arqueiro', 'Arqueiro'), ('Mercador', 'Mercador'), ('Acólito', 'Acólito'), ('Gatuno', 'Gatuno')], max_length=20, verbose_name='Classe')),
                ('zeny', models.BigIntegerField(default=0, verbose_name='Zeny')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personagens', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Personagem',
                'verbose_name_plural': 'Personagens',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('Arma', 'Arma'), ('Armadura', 'Armadura'), ('Acessório', 'Acessório'), ('Consumível', 'Consumível'), ('Outros', 'Outros')], default='Outros', max_length=20, verbose_name='Tipo')),
                ('raridade', models.CharField(default='Comum', max_length=20, verbose_name='Raridade')),
                ('preco_base', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço Base')),
                ('imagem_url', models.URLField(blank=True, null=True, verbose_name='URL da Imagem')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.categoriadeitem', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.item', verbose_name='Item')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_inventario', to='inventario.personagem', verbose_name='Personagem')),
            ],
            options={
                'verbose_name': 'Item no Inventário',
                'verbose_name_plural': 'Itens no Inventário',
                'unique_together': {('personagem', 'item')},
            },
        ),
    ]
