# Generated by Django 4.2.27 on 2025-12-09 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaDeVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço Unitário')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('VENDIDA', 'Vendida'), ('CANCELADA', 'Cancelada')], default='ATIVA', max_length=10, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.item', verbose_name='Item')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_venda', to='inventario.personagem', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Oferta de Venda',
                'verbose_name_plural': 'Ofertas de Venda',
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_nome_snapshot', models.CharField(help_text='Nome do item no momento da compra', max_length=100, verbose_name='Nome do Item (Snapshot)')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço Total')),
                ('data_transacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Transação')),
                ('comprador_personagem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacoes_como_comprador', to='inventario.personagem', verbose_name='Comprador')),
                ('oferta_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='mercado.ofertadevenda', verbose_name='Oferta de Origem')),
                ('vendedor_personagem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacoes_como_vendedor', to='inventario.personagem', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
            },
        ),
        migrations.CreateModel(
            name='HistoricoDePrecos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_medio', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço Médio')),
                ('data_registro', models.DateField(auto_now_add=True, verbose_name='Data do Registro')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_precos', to='inventario.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Histórico de Preço',
                'verbose_name_plural': 'Histórico de Preços',
            },
        ),
    ]
